# Generated by Django 4.2.5 on 2023-09-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptTaskModel',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('status', models.CharField(default='в ожидании', editable=False, max_length=20, verbose_name='Статус')),
                ('encrypted_data', models.TextField(blank=True, verbose_name='Данные для зашифровки')),
                ('key', models.CharField(blank=True, max_length=100, verbose_name='Ключ для расшифровки')),
            ],
        ),
    ]
